spring:
  application:
    name: api

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,prometheus,info,metric
  endpoint:
    health:
      probes:
        enabled: true
      enabled: true
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
